// <auto-generated />
using HelpDesk.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.API.Migrations
{
     [DbContext(typeof(AppDbContext))]
     partial class AppDbContextModelSnapshot : ModelSnapshot
     {
          protected override void BuildModel(ModelBuilder modelBuilder)
          {
#pragma warning disable 612, 618
               modelBuilder
                   .HasAnnotation("ProductVersion", "9.0.16")
                   .HasAnnotation("Relational:MaxIdentifierLength", 128);

               SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

               modelBuilder.Entity("HelpDesk.API.Models.User", b =>
                   {
                        b.Property<int>("Id")
                         .ValueGeneratedOnAdd()
                         .HasColumnType("int");

                        SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                        b.Property<string>("Email")
                         .IsRequired()
                         .HasColumnType("nvarchar(max)");

                        b.Property<string>("FullName")
                         .IsRequired()
                         .HasColumnType("nvarchar(max)");

                        b.Property<string>("Password")
                         .IsRequired()
                         .HasColumnType("nvarchar(max)");

                        b.Property<int>("RoleId")
                         .HasColumnType("int");

                        b.HasKey("Id");

                        b.ToTable("Users");
                   });
#pragma warning restore 612, 618
          }
     }
}
